#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackyHack.Resource", IsApplication=true)]

namespace HackyHack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::RPCoreLib.Resource.Drawable.rising_phoenix_logo = global::HackyHack.Resource.Drawable.rising_phoenix_logo;
			global::RPCoreLib.Resource.Drawable.white_square = global::HackyHack.Resource.Drawable.white_square;
			global::RPCoreLib.Resource.String.library_name = global::HackyHack.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_modem = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_router = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_switch = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rising_phoenix_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tb_bracket_left_down = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tb_bracket_left_up = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tb_bracket_right_down = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tb_bracket_right_up = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tb_left_off = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tb_left_on = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tb_right_off = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tb_right_on = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int white_square = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int window_map = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
